# Re-import necessary library and define the questions again after reset
import pandas as pd

# Define 100 technical and project-related questions focusing on data science projects
experience_questions = [
    "Can you walk us through your professional journey so far?",
    "What roles have you held in your previous jobs?",
    "How has your education prepared you for this role?",
    "What was the biggest challenge you faced in your previous job, and how did you overcome it?",
    "Can you describe a time when you took initiative in a project?",
    "What experience do you have working in teams?",
    "How do you handle conflicts in a professional setting?",
    "Have you ever mentored or trained someone? Can you share that experience?",
    "What is the most significant achievement in your career so far?",
    "Can you describe a time when you had to meet a tight deadline?",
    "What experience do you have with client-facing roles?",
    "Can you explain a situation where you had to adapt quickly to a change?",
    "How do you prioritize tasks when managing multiple deadlines?",
    "What role do you usually take in a team setting?",
    "Have you ever led a team? What challenges did you face?",
    "What is your experience with presenting or communicating technical information?",
    "Can you describe a project where you exceeded expectations?",
    "How do you stay updated in your field?",
    "What was the most challenging project you've worked on?",
    "Can you explain a situation where you learned from a failure?",
    "How do you approach problem-solving in high-pressure situations?",
    "What was your role in your last major project?",
    "How do you ensure you meet project goals and deadlines?",
    "Can you provide an example of a time you handled criticism constructively?",
    "What steps do you take to ensure quality in your work?",
    "How do you balance independent work and collaboration?",
    "Can you describe a time when you improved a process or system?",
    "What experience do you have with project management tools?",
    "Have you worked with cross-functional teams? How did you handle it?",
    "What strategies do you use to manage stress at work?",
    "Can you share an example of a successful project you've led?",
    "What is your experience with working on long-term projects?",
    "How do you handle ambiguous tasks or requirements?",
    "What is the most valuable lesson you've learned from your previous experiences?",
    "Can you describe a time when you had to persuade someone to adopt your idea?",
    "How do you approach feedback from colleagues or supervisors?",
    "What experience do you have with remote work or virtual teams?",
    "Can you explain a time when you managed a difficult stakeholder?",
    "What is your experience with documentation and reporting in your projects?",
    "Have you ever worked on a project that failed? What did you learn?",
    "How do you ensure effective communication within a team?",
    "What has been your experience with career growth in your previous roles?",
    "Can you share an example of a technical problem you solved?",
    "What experience do you have with presenting findings to a non-technical audience?",
    "Have you ever had to work under minimal supervision? How did you handle it?",
    "Can you describe a time when you worked on a project outside your expertise?",
    "How do you handle repetitive or mundane tasks?",
    "What experience do you have with budget or resource management?",
    "Can you share a time when you resolved a workplace disagreement?",
    "What role have you played in scaling or improving a product or service?",
    "Have you ever worked on a project that required cross-cultural collaboration?",
    "What do you consider your greatest strength as a professional?",
    "Can you describe a time when you went above and beyond for a project?",
    "What experience do you have with stakeholder management?",
    "How do you handle situations where you have to deliver bad news to a client or team?",
    "What tools or methods do you use to track your progress on tasks?",
    "Have you ever worked on multiple projects simultaneously? How did you manage your time?",
    "Can you explain how you have contributed to a team's success in the past?",
    "What is your experience with conducting research in your field?",
    "Can you describe a time when you identified and fixed a critical issue?",
    "What is your experience with implementing new tools or technologies?",
    "How do you measure success in your work?",
    "What steps do you take to ensure effective collaboration with your team?",
    "Can you share an example of a time when you handled a major project risk?",
    "What is your experience with providing constructive feedback?",
    "Have you ever had to train others on new systems or processes?",
    "Can you describe a time when you had to deal with unexpected project scope changes?",
    "How do you approach delegating tasks within a team?",
    "What is your experience with agile or scrum methodologies?",
    "Have you worked on projects where you had to gather requirements from clients?",
    "How do you track and measure the impact of your work?",
    "What is your experience with writing or contributing to technical proposals?",
    "Can you describe a time when you streamlined a process to save time or resources?",
    "What is your experience with conflict resolution in a team setting?",
    "How do you handle situations where a project doesn't go as planned?",
    "What methods do you use to stay organized and meet deadlines?",
    "Can you explain a time when you had to upskill quickly to meet a project's needs?",
    "What is your experience with implementing best practices in your work?",
    "Can you describe a time when you took on additional responsibilities at work?",
    "How do you ensure continuous learning and development in your career?",
    "Can you share an example of a time when you improved team efficiency?",
    "What is your experience with creating or maintaining standard operating procedures?",
    "Can you describe a time when you had to advocate for a resource or tool?",
    "What steps do you take to identify and address project bottlenecks?",
    "How do you ensure alignment between team goals and organizational objectives?",
    "Can you describe a time when you managed a large-scale project?",
    "What is your experience with identifying and mitigating risks?",
    "How do you approach creating and maintaining professional relationships?",
    "Have you ever been involved in hiring or onboarding new team members?",
    "Can you share an example of a project where you delivered measurable results?",
    "How do you handle competing priorities in your workload?",
    "What is your experience with industry-specific certifications or training?",
    "Can you describe a time when you took ownership of a challenging situation?"
]

# Create a DataFrame
df_technical = pd.DataFrame(experience_questions, columns=["Questions"])

# Save as CSV
file_path_technical = "Top_100_experience_questions.csv"
df_technical.to_csv(file_path_technical, index=False)

file_path_technical
